name: Running Test Cases
on:
    push:
        branches: [main, stage]
jobs:
    testing-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Install Dependencies
              run: npm install

            - name: Creating the .env file
              run: echo "${{ secrets.STAGE_ENV }}" | base64 --decode > .env

            - name: Run build
              run: npm run build

    deployment-stage:
        if: github.event.ref == 'refs/heads/stage'
        runs-on: ubuntu-latest
        needs: testing-build
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Creating the leafs-ehr-web-stage .env file
              run: echo "${{ secrets.STAGE_ENV }}" | base64 --decode > .env

            - name: Login
              uses: google-github-actions/setup-gcloud@v0
              with:
                  project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
                  service_account_email: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_EMAIL }}
                  service_account_key: ${{ secrets.GCP_CREDENTIALS }}

            - name: Configure Docker
              run: gcloud auth configure-docker --quiet

            - name: Build Docker image
              run: docker buildx build --platform linux/amd64 -t leafs-ehr-web-stage:v1.0.0 .

            - name: Tag Docker image
              run: docker tag leafs-ehr-web-stage:v1.0.0 gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}/leafs-ehr-web-stage:v1.0.0

            - name: Push Docker image
              run: docker push gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}/leafs-ehr-web-stage:v1.0.0

            - name: Deploy
              run: |
                  gcloud run deploy leafs-ehr-web-stage --image gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}/leafs-ehr-web-stage:v1.0.0 \
                  --platform managed \
                  --allow-unauthenticated \
                  --memory 4Gi \
                  --region us-central1 \
                  --cpu 4 \
                  --port 3000

    deployment-production:
        if: github.event.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        needs: testing-build
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Creating the leafs-ehr-web-production .env file
              run: echo "${{ secrets.PRODUCTION_ENV }}" | base64 --decode > .env

            - name: Login
              uses: google-github-actions/setup-gcloud@v0
              with:
                  project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
                  service_account_email: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_EMAIL }}
                  service_account_key: ${{ secrets.GCP_CREDENTIALS }}

            - name: Configure Docker
              run: gcloud auth configure-docker --quiet

            - name: Build Docker image
              run: docker buildx build --platform linux/amd64 -t leafs-ehr-web-production:v1.0.0 .

            - name: Tag Docker image
              run: docker tag leafs-ehr-web-production:v1.0.0 gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}/leafs-ehr-web-production:v1.0.0

            - name: Push Docker image
              run: docker push gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}/leafs-ehr-web-production:v1.0.0

            - name: Deploy
              run: |
                  gcloud run deploy leafs-ehr-web-production --image gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}/leafs-ehr-web-production:v1.0.0 \
                  --platform managed \
                  --allow-unauthenticated \
                  --memory 4Gi \
                  --region us-central1 \
                  --cpu 4 \
                  --port 3000
