name: Running Test Cases
on:
    pull_request:
        branches: [main, stage]
jobs:
    testing-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - name: Install Dependencies
              run: npm install
            - name: Creating the .env file
              run: echo "${{ secrets.STAGE_ENV }}" | base64 --decode > .env
            - name: Run build
              run: npm run build
